#!/bin/sh
# Lance CloneGator, installé dans /usr/lib/clonegator.
export PYTHONPATH=/usr/lib/clonegator${PYTHONPATH:+:$PYTHONPATH}
# Pas de __pycache__ dans /usr/lib : dpkg ne le connaîtrait pas.
export PYTHONDONTWRITEBYTECODE=1
exec /usr/bin/python3 -m clonegator "$@"
